name: CI

on: [push, pull_request]

jobs:

  main:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin

      - name: Execute Gradle build
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.12
          arguments: build
